files:
  - source: /src/content/docs/**/*.*
    ignore:
      - /src/content/docs/**/%two_letters_code%_%original_file_name%
    translation: /src/content/docs/%two_letters_code%_%original_file_name%
